name: Build and deploy the Ravenlog project
inputs:
  working-directory:
    description: "The working directory to run the deploy script in"
    required: false
    default: "."
  deploy-branch:
    description: "The branch to deploy to"
    required: false
    default: "deploy-ravenlog"
  github-token:
    description: "The GitHub token to use for the deploy"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: ravenlog
    - run: bash ./actions/deploy/deploy.sh
      shell: bash
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        DEPLOY_BRANCH: ${{ inputs.deploy-branch }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
