name: Backend
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check
        working-directory: backend
        run: nix flake check
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        working-directory: backend
        run: nix build .
