name: Example Ravenlog Build
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: brack-lang/ravenlog/actions/deploy@main
        with:
          working-directory: example
          deploy-branch: deploy-ravenlog
          github-token: ${{ secrets.GITHUB_TOKEN }}
