name: Example Ravenlog Build
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v2
        with:
          name: ravenlog
      - name: Deploy
        uses: brack-lang/ravenlog/actions/deploy@main
        with:
          working-directory: example
          deploy-branch: deploy-ravenlog
